# Salve como: Dockerfile.atacante
FROM ubuntu:22.04

# Instala o hping3
RUN apt-get update && \
    apt-get install -y hping3 && \
    rm -rf /var/lib/apt/lists/*

# Inicia o terminal
CMD ["/bin/bash"]